//def(main template for normal using)
//graph(dfs bfs shob ache)
//treedepth(tree er root theke node gular depth ber korar)
//sv(sieve er code)
//bi(bipartite graph)
//bitmask(all possible sub sequence with bitmask)
//lamda(for using lamda function)
//pbds(oredered set,map)
//bfs(shortest path with bfs)
//spf(smallest prime factor)
//topbf(topshort with bruteforce)
//topfast(topshort in a fast way)
//2d vec(2d vector example)
//cycle(directed graph cycle detection)
//gp(generics of programming stl)
//rec(a code with recursive solution)